@webapi_HostAddress = http://localhost:5205

GET {{webapi_HostAddress}}/api/pacientes
Accept: application/json
###

POST {{webapi_HostAddress}}/api/pacientes
Content-Type: application/json

{
    "nombre": "Mariano",
    "apellido": "Dominguez",
    "dni": "12365778",
    "fechaNacimiento": "1990-01-01",
    "email": "mariano.dominguez@example.com",
    "telefono": "2216748875",
    "direccion": "Calle Falsa 123"
}
###
